# Generated by Django 2.2.1 on 2021-09-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_auto_20210915_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_q', to='pools.Option'),
        ),
    ]
