# Generated by Django 2.2.1 on 2021-09-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_auto_20210915_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
