# Generated by Django 2.2.1 on 2021-09-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_auto_20210916_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='pools.Question'),
            preserve_default=False,
        ),
    ]
