# Generated by Django 2.2.1 on 2021-09-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_auto_20210916_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_q', to='pools.Option'),
        ),
    ]
